/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContentType = IDL.Variant({
  'mouse' : IDL.Null,
  'bedBugs' : IDL.Null,
  'scorpion' : IDL.Null,
  'cockroach' : IDL.Null,
  'hornetWasp' : IDL.Null,
  'venomousSnake' : IDL.Null,
  'mosquito' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrintableGuide = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'file' : ExternalBlob,
});
export const ContentSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'images' : IDL.Vec(ExternalBlob),
});
export const Technician = IDL.Record({
  'id' : IDL.Text,
  'serviceArea' : IDL.Vec(IDL.Nat),
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'zipCode' : IDL.Nat,
  'state' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'specialties' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addTechnician' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'getAllGuides' : IDL.Func([], [IDL.Vec(PrintableGuide)], ['query']),
  'getAllSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
  'getGuide' : IDL.Func([IDL.Text], [IDL.Opt(PrintableGuide)], ['query']),
  'getGuidesByContentType' : IDL.Func(
      [ContentType],
      [IDL.Vec(PrintableGuide)],
      ['query'],
    ),
  'getSection' : IDL.Func([IDL.Text], [IDL.Opt(ContentSection)], ['query']),
  'getSectionsByContentType' : IDL.Func(
      [ContentType],
      [IDL.Vec(ContentSection)],
      ['query'],
    ),
  'getTechniciansByZip' : IDL.Func([IDL.Nat], [IDL.Vec(Technician)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContentType = IDL.Variant({
    'mouse' : IDL.Null,
    'bedBugs' : IDL.Null,
    'scorpion' : IDL.Null,
    'cockroach' : IDL.Null,
    'hornetWasp' : IDL.Null,
    'venomousSnake' : IDL.Null,
    'mosquito' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrintableGuide = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'file' : ExternalBlob,
  });
  const ContentSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Technician = IDL.Record({
    'id' : IDL.Text,
    'serviceArea' : IDL.Vec(IDL.Nat),
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'zipCode' : IDL.Nat,
    'state' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'specialties' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addTechnician' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'getAllGuides' : IDL.Func([], [IDL.Vec(PrintableGuide)], ['query']),
    'getAllSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
    'getGuide' : IDL.Func([IDL.Text], [IDL.Opt(PrintableGuide)], ['query']),
    'getGuidesByContentType' : IDL.Func(
        [ContentType],
        [IDL.Vec(PrintableGuide)],
        ['query'],
      ),
    'getSection' : IDL.Func([IDL.Text], [IDL.Opt(ContentSection)], ['query']),
    'getSectionsByContentType' : IDL.Func(
        [ContentType],
        [IDL.Vec(ContentSection)],
        ['query'],
      ),
    'getTechniciansByZip' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Technician)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };