/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContentSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'contentType' : ContentType,
  'images' : Array<ExternalBlob>,
}
export type ContentType = { 'mouse' : null } |
  { 'bedBugs' : null } |
  { 'scorpion' : null } |
  { 'cockroach' : null } |
  { 'hornetWasp' : null } |
  { 'venomousSnake' : null } |
  { 'mosquito' : null };
export type ExternalBlob = Uint8Array;
export interface PrintableGuide {
  'id' : string,
  'title' : string,
  'content' : string,
  'contentType' : ContentType,
  'file' : ExternalBlob,
}
export interface QuizQuestion {
  'id' : string,
  'question' : string,
  'explanation' : string,
  'section' : QuizSectionType,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'section' : QuizSectionType,
  'score' : bigint,
  'totalQuestions' : bigint,
  'completedQuestions' : bigint,
}
export type QuizSectionType = { 'habitatsHabits' : null } |
  { 'identifyBedBugs' : null } |
  { 'treatmentPreparation' : null } |
  { 'prevention' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'calculateQuizResult' : ActorMethod<
    [Array<string>, QuizSectionType],
    QuizResult
  >,
  'getAllGuides' : ActorMethod<[], Array<PrintableGuide>>,
  'getAllQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getAllSections' : ActorMethod<[], Array<ContentSection>>,
  'getGuide' : ActorMethod<[string], [] | [PrintableGuide]>,
  'getGuidesByContentType' : ActorMethod<[ContentType], Array<PrintableGuide>>,
  'getQuestionById' : ActorMethod<[string], [] | [QuizQuestion]>,
  'getQuizQuestionsBySection' : ActorMethod<
    [QuizSectionType],
    Array<QuizQuestion>
  >,
  'getSection' : ActorMethod<[string], ContentSection>,
  'getSectionsByContentType' : ActorMethod<
    [ContentType],
    Array<ContentSection>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];