/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContentType = IDL.Variant({
  'mouse' : IDL.Null,
  'bedBugs' : IDL.Null,
  'scorpion' : IDL.Null,
  'cockroach' : IDL.Null,
  'hornetWasp' : IDL.Null,
  'venomousSnake' : IDL.Null,
  'mosquito' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrintableGuide = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'file' : ExternalBlob,
});
export const ContentSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'images' : IDL.Vec(ExternalBlob),
});
export const AppointmentStatus = IDL.Variant({
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'pendingConfirmation' : IDL.Null,
});
export const Appointment = IDL.Record({
  'status' : AppointmentStatus,
  'appointmentTimestamp' : IDL.Int,
  'submissionTimestamp' : IDL.Int,
  'homeAddress' : IDL.Text,
  'caller' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'technicianId' : IDL.Opt(IDL.Text),
  'isTechnician' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'threadId' : IDL.Text,
  'isTechnician' : IDL.Bool,
  'senderId' : IDL.Principal,
});
export const Technician = IDL.Record({
  'id' : IDL.Text,
  'serviceArea' : IDL.Vec(IDL.Nat),
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'zipCode' : IDL.Nat,
  'state' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'specialties' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTechnician' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmAppointment' : IDL.Func([IDL.Principal], [], []),
  'fetchZipCodeBoundary' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'getActiveTechniciansForChat' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllGuides' : IDL.Func([], [IDL.Vec(PrintableGuide)], ['query']),
  'getAllSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuide' : IDL.Func([IDL.Text], [IDL.Opt(PrintableGuide)], ['query']),
  'getGuidesByContentType' : IDL.Func(
      [ContentType],
      [IDL.Vec(PrintableGuide)],
      ['query'],
    ),
  'getMessagesForThread' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getSection' : IDL.Func([IDL.Text], [IDL.Opt(ContentSection)], ['query']),
  'getSectionsByContentType' : IDL.Func(
      [ContentType],
      [IDL.Vec(ContentSection)],
      ['query'],
    ),
  'getTechniciansByZip' : IDL.Func([IDL.Nat], [IDL.Vec(Technician)], ['query']),
  'getThreadList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Bool, IDL.Text, IDL.Text], [], []),
  'submitAppointment' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContentType = IDL.Variant({
    'mouse' : IDL.Null,
    'bedBugs' : IDL.Null,
    'scorpion' : IDL.Null,
    'cockroach' : IDL.Null,
    'hornetWasp' : IDL.Null,
    'venomousSnake' : IDL.Null,
    'mosquito' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrintableGuide = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'file' : ExternalBlob,
  });
  const ContentSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'images' : IDL.Vec(ExternalBlob),
  });
  const AppointmentStatus = IDL.Variant({
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'pendingConfirmation' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'status' : AppointmentStatus,
    'appointmentTimestamp' : IDL.Int,
    'submissionTimestamp' : IDL.Int,
    'homeAddress' : IDL.Text,
    'caller' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'technicianId' : IDL.Opt(IDL.Text),
    'isTechnician' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'threadId' : IDL.Text,
    'isTechnician' : IDL.Bool,
    'senderId' : IDL.Principal,
  });
  const Technician = IDL.Record({
    'id' : IDL.Text,
    'serviceArea' : IDL.Vec(IDL.Nat),
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'zipCode' : IDL.Nat,
    'state' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'specialties' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTechnician' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmAppointment' : IDL.Func([IDL.Principal], [], []),
    'fetchZipCodeBoundary' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'getActiveTechniciansForChat' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllGuides' : IDL.Func([], [IDL.Vec(PrintableGuide)], ['query']),
    'getAllSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuide' : IDL.Func([IDL.Text], [IDL.Opt(PrintableGuide)], ['query']),
    'getGuidesByContentType' : IDL.Func(
        [ContentType],
        [IDL.Vec(PrintableGuide)],
        ['query'],
      ),
    'getMessagesForThread' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getSection' : IDL.Func([IDL.Text], [IDL.Opt(ContentSection)], ['query']),
    'getSectionsByContentType' : IDL.Func(
        [ContentType],
        [IDL.Vec(ContentSection)],
        ['query'],
      ),
    'getTechniciansByZip' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Technician)],
        ['query'],
      ),
    'getThreadList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Bool, IDL.Text, IDL.Text], [], []),
    'submitAppointment' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };