/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'status' : AppointmentStatus,
  'appointmentTimestamp' : bigint,
  'submissionTimestamp' : bigint,
  'homeAddress' : string,
  'caller' : Principal,
}
export type AppointmentStatus = { 'completed' : null } |
  { 'confirmed' : null } |
  { 'pendingConfirmation' : null };
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
  'threadId' : string,
  'isTechnician' : boolean,
  'senderId' : Principal,
}
export interface ContentSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'contentType' : ContentType,
  'images' : Array<ExternalBlob>,
}
export type ContentType = { 'mouse' : null } |
  { 'bedBugs' : null } |
  { 'scorpion' : null } |
  { 'cockroach' : null } |
  { 'hornetWasp' : null } |
  { 'venomousSnake' : null } |
  { 'mosquito' : null };
export type ExternalBlob = Uint8Array;
export interface PrintableGuide {
  'id' : string,
  'title' : string,
  'content' : string,
  'contentType' : ContentType,
  'file' : ExternalBlob,
}
export interface Technician {
  'id' : string,
  'serviceArea' : Array<bigint>,
  'latitude' : number,
  'city' : string,
  'businessName' : string,
  'zipCode' : bigint,
  'state' : string,
  'longitude' : number,
  'address' : string,
  'specialties' : string,
  'phoneNumber' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'technicianId' : [] | [string],
  'isTechnician' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTechnician' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<bigint>,
      string,
      bigint,
      string,
      number,
      number,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmAppointment' : ActorMethod<[Principal], undefined>,
  'fetchZipCodeBoundary' : ActorMethod<[bigint, string], string>,
  'getActiveTechniciansForChat' : ActorMethod<[], Array<string>>,
  'getAllGuides' : ActorMethod<[], Array<PrintableGuide>>,
  'getAllSections' : ActorMethod<[], Array<ContentSection>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuide' : ActorMethod<[string], [] | [PrintableGuide]>,
  'getGuidesByContentType' : ActorMethod<[ContentType], Array<PrintableGuide>>,
  'getMessagesForThread' : ActorMethod<[string], Array<ChatMessage>>,
  'getSection' : ActorMethod<[string], [] | [ContentSection]>,
  'getSectionsByContentType' : ActorMethod<
    [ContentType],
    Array<ContentSection>
  >,
  'getTechniciansByZip' : ActorMethod<[bigint], Array<Technician>>,
  'getThreadList' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[boolean, string, string], undefined>,
  'submitAppointment' : ActorMethod<[bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];