/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PrintableGuide {
    id: string;
    title: string;
    content: string;
    contentType: ContentType;
    file: ExternalBlob;
}
export interface QuizQuestion {
    id: string;
    question: string;
    explanation: string;
    section: QuizSectionType;
    correctAnswerIndex: bigint;
    options: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizResult {
    section: QuizSectionType;
    score: bigint;
    totalQuestions: bigint;
    completedQuestions: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ContentSection {
    id: string;
    title: string;
    content: string;
    contentType: ContentType;
    images: Array<ExternalBlob>;
}
export enum ContentType {
    mouse = "mouse",
    bedBugs = "bedBugs",
    scorpion = "scorpion",
    cockroach = "cockroach",
    hornetWasp = "hornetWasp",
    venomousSnake = "venomousSnake",
    mosquito = "mosquito"
}
export enum QuizSectionType {
    habitatsHabits = "habitatsHabits",
    identifyBedBugs = "identifyBedBugs",
    treatmentPreparation = "treatmentPreparation",
    prevention = "prevention"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    calculateQuizResult(userAnswers: Array<string>, sectionType: QuizSectionType): Promise<QuizResult>;
    getAllGuides(): Promise<Array<PrintableGuide>>;
    getAllQuizQuestions(): Promise<Array<QuizQuestion>>;
    getAllSections(): Promise<Array<ContentSection>>;
    getGuide(id: string): Promise<PrintableGuide | null>;
    getGuidesByContentType(contentType: ContentType): Promise<Array<PrintableGuide>>;
    getQuestionById(questionId: string): Promise<QuizQuestion | null>;
    getQuizQuestionsBySection(sectionType: QuizSectionType): Promise<Array<QuizQuestion>>;
    getSection(id: string): Promise<ContentSection>;
    getSectionsByContentType(contentType: ContentType): Promise<Array<ContentSection>>;
}
import type { ContentSection as _ContentSection, ContentType as _ContentType, ExternalBlob as _ExternalBlob, PrintableGuide as _PrintableGuide, QuizQuestion as _QuizQuestion, QuizResult as _QuizResult, QuizSectionType as _QuizSectionType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async calculateQuizResult(arg0: Array<string>, arg1: QuizSectionType): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateQuizResult(arg0, to_candid_QuizSectionType_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_QuizResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateQuizResult(arg0, to_candid_QuizSectionType_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_QuizResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGuides(): Promise<Array<PrintableGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuides();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuides();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuizQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizQuestions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizQuestions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSections(): Promise<Array<ContentSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSections();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSections();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuide(arg0: string): Promise<PrintableGuide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuide(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuide(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuidesByContentType(arg0: ContentType): Promise<Array<PrintableGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidesByContentType(to_candid_ContentType_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidesByContentType(to_candid_ContentType_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionById(arg0: string): Promise<QuizQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionById(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionById(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestionsBySection(arg0: QuizSectionType): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestionsBySection(to_candid_QuizSectionType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestionsBySection(to_candid_QuizSectionType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSection(arg0: string): Promise<ContentSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getSection(arg0);
                return from_candid_ContentSection_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSection(arg0);
            return from_candid_ContentSection_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSectionsByContentType(arg0: ContentType): Promise<Array<ContentSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionsByContentType(to_candid_ContentType_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionsByContentType(to_candid_ContentType_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ContentSection_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentSection): Promise<ContentSection> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PrintableGuide_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintableGuide): Promise<PrintableGuide> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_QuizQuestion_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_QuizResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizResult): QuizResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuizSectionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizSectionType): QuizSectionType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrintableGuide]): Promise<PrintableGuide | null> {
    return value.length === 0 ? null : await from_candid_PrintableGuide_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizQuestion]): QuizQuestion | null {
    return value.length === 0 ? null : from_candid_QuizQuestion_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    section: _QuizSectionType;
    score: bigint;
    totalQuestions: bigint;
    completedQuestions: bigint;
}): {
    section: QuizSectionType;
    score: bigint;
    totalQuestions: bigint;
    completedQuestions: bigint;
} {
    return {
        section: from_candid_QuizSectionType_n12(_uploadFile, _downloadFile, value.section),
        score: value.score,
        totalQuestions: value.totalQuestions,
        completedQuestions: value.completedQuestions
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    contentType: _ContentType;
    file: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    content: string;
    contentType: ContentType;
    file: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        contentType: from_candid_ContentType_n17(_uploadFile, _downloadFile, value.contentType),
        file: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.file)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    question: string;
    explanation: string;
    section: _QuizSectionType;
    correctAnswerIndex: bigint;
    options: Array<string>;
}): {
    id: string;
    question: string;
    explanation: string;
    section: QuizSectionType;
    correctAnswerIndex: bigint;
    options: Array<string>;
} {
    return {
        id: value.id,
        question: value.question,
        explanation: value.explanation,
        section: from_candid_QuizSectionType_n12(_uploadFile, _downloadFile, value.section),
        correctAnswerIndex: value.correctAnswerIndex,
        options: value.options
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    contentType: _ContentType;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    content: string;
    contentType: ContentType;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        contentType: from_candid_ContentType_n17(_uploadFile, _downloadFile, value.contentType),
        images: await from_candid_vec_n26(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    habitatsHabits: null;
} | {
    identifyBedBugs: null;
} | {
    treatmentPreparation: null;
} | {
    prevention: null;
}): QuizSectionType {
    return "habitatsHabits" in value ? QuizSectionType.habitatsHabits : "identifyBedBugs" in value ? QuizSectionType.identifyBedBugs : "treatmentPreparation" in value ? QuizSectionType.treatmentPreparation : "prevention" in value ? QuizSectionType.prevention : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mouse: null;
} | {
    bedBugs: null;
} | {
    scorpion: null;
} | {
    cockroach: null;
} | {
    hornetWasp: null;
} | {
    venomousSnake: null;
} | {
    mosquito: null;
}): ContentType {
    return "mouse" in value ? ContentType.mouse : "bedBugs" in value ? ContentType.bedBugs : "scorpion" in value ? ContentType.scorpion : "cockroach" in value ? ContentType.cockroach : "hornetWasp" in value ? ContentType.hornetWasp : "venomousSnake" in value ? ContentType.venomousSnake : "mosquito" in value ? ContentType.mosquito : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrintableGuide>): Promise<Array<PrintableGuide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PrintableGuide_n15(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n21(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentSection>): Promise<Array<ContentSection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ContentSection_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, x)));
}
function to_candid_ContentType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_QuizSectionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizSectionType): _QuizSectionType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    mouse: null;
} | {
    bedBugs: null;
} | {
    scorpion: null;
} | {
    cockroach: null;
} | {
    hornetWasp: null;
} | {
    venomousSnake: null;
} | {
    mosquito: null;
} {
    return value == ContentType.mouse ? {
        mouse: null
    } : value == ContentType.bedBugs ? {
        bedBugs: null
    } : value == ContentType.scorpion ? {
        scorpion: null
    } : value == ContentType.cockroach ? {
        cockroach: null
    } : value == ContentType.hornetWasp ? {
        hornetWasp: null
    } : value == ContentType.venomousSnake ? {
        venomousSnake: null
    } : value == ContentType.mosquito ? {
        mosquito: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizSectionType): {
    habitatsHabits: null;
} | {
    identifyBedBugs: null;
} | {
    treatmentPreparation: null;
} | {
    prevention: null;
} {
    return value == QuizSectionType.habitatsHabits ? {
        habitatsHabits: null
    } : value == QuizSectionType.identifyBedBugs ? {
        identifyBedBugs: null
    } : value == QuizSectionType.treatmentPreparation ? {
        treatmentPreparation: null
    } : value == QuizSectionType.prevention ? {
        prevention: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
